IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'db_23102024')
	CREATE DATABASE db_23102024;
	GO

USE db_23102024;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'tb_itens')
	CREATE TABLE tb_itens
		(
			id INT PRIMARY KEY IDENTITY,
			nome VARCHAR(MAX),
			qtd INT
		)

DBCC USEROPTIONS

SET TRANSACTION ISOLATION LEVEL
	READ UNCOMMITTED;
